### ISSUE TITLE
Mega2560, more than 3 motors

### ISSUE THREAD

**Issue by santis365** [gin66/FastAccelStepper#136]
Is there any chances to run 4 motors with arduino mega 2560?

**Comment by gin66** [comment]
Yes and no. The Arduino mega 2560 has sufficient timers to support up to 12 steppers. The issue is, that the current avr code only supports one timer and as such only three steppers.

The question is, do you need 4 motors simultaneously ? If yes, which step rate is needed ? The avr code limits the step rate dynamically depending on the number of parallel steppers. _allows up to 76000 generated steps per second for single stepper operation, 37000 for dual stepper and 25000 for three steppers_. So a fourth stepper may need to further reduce to approx. 19kSteps/s.

**Comment by gin66** [comment]
great. thanks for the update
