### ISSUE TITLE
ESP8266 ?

### ISSUE THREAD

**Issue by andreas-git** [gin66/FastAccelStepper#38]
Hi,

is there a way to use this Prject on an ESP8266 ?

Best Regards 

Andreas

**Comment by gin66** [comment]
In theory yes, but the esp32 module will not work, because the esp8266 does not have a pulse counter module. Thus an avr like way could be used, which requires one interrupt per step. The esp8266 has four pwm timers, so it could be done.

The way would be to create a StepperISR_esp8266.cpp file, which implements the required function to convert step commands (ticks+steps+direction) into output pulses.

As I have no esp8266, I cannot develop this.
