### ISSUE TITLE
RampGenerator.cpp code inquiry

### ISSUE THREAD

**Issue by kpu0411** [gin66/FastAccelStepper#95]
file : RampGenerator.cpp

static void _getNextCommand(const struct ramp_ro_s *ramp,
                            const struct ramp_rw_s *rw,
                            const struct queue_end_s *queue_end,
                            NextCommand *command)

Please tell me what you are using planning_steps for. I don't understand the code.
What does 2ms mean?

**Comment by gin66** [comment]
The code uses this formula to calculate from steps to the required speed:
```
v = sqrt(2 * s * a)
```

On call to `getNextCommand()`, the code is currently at some point on the ramp e.g. sx and needs to issue the speed for the next point sy. So the speeds are then:
```
vx = sqrt(2 * sx * a)
vy = sqrt(2 * sy * a)
```

The problem is now to determine this next point sy in a reasonable distance from sx. And this distance is the (forward) planning_steps.
So simply:
```
sy = sx + planning_steps
```

This planning_steps is chosen in a way, that a typical command to the stepper queue covers 2ms. On high speeds, the planning_steps are greater than 1 and for slower speeds equal to 1.
